### PR TITLE
Make the packaging shell file work on osx

### PR DESCRIPTION
**Pull request by zafarella**
*Description of changes:*
Make the packaging work on osx

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by marcomagdy** [comment]
But why?
I intentionally ignored making it work on MacOS. Otherwise, it will package successfully only to crash when you deploy it.
Lambda runs on Linux. The binaries you package on MacOS will never work.
Is there a use case that I'm missing?

**Comment by zafarella** [comment]
this is why working at night is not good..)
So we don't have linux as daily using machine, mbe add cross compilation or may be add container?
My point is to have less setup and get it working on osx

**Comment by marcomagdy** [comment]
I have a couple of [docker images](https://github.com/awslabs/aws-lambda-cpp/blob/master/ci/docker/amazon-linux-2017.03) that I use for CI.

See if you can improve on those to streamline the process?!
Cross-compilation can be tricky, and there's already a learning curve to C++ on Lambda. I'd rather stay away from that.
That being said, I don't want to shut the door on that option. It might a productivity boon if it's done right.

So, I guess my answer is, see what you can come up with :)
I'm happy to review it.

**Comment by daleobrien** [comment]
You might find https://github.com/daleobrien/aws-lambda-cpp-hello-world which I created.  It will build a "hello world" lambda function on OSX using only docker and produce a zip file you can then use.

**Pull request closed without merging**
