### PR TITLE
Add building and packaging a demo project to CI and revert #136

### PR DESCRIPTION
**Pull request by kkarbowiak**
*Issue #, if available:* #182

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kkarbowiak** [comment]
Thew newly added build-demo job fails, but my best guess is that this is related to #179. In any case, detecting such issues is the main reason for adding this job.

**Comment by marcomagdy** [comment]
We're failing on some new clang-tidy checks.
The warnings are benign though. One of them is about variable name length (we should fix that) and the other is about easily swappable parameters. I am not supportive of making code changes to fix the latter.

**Comment by marcomagdy** [comment]
Thanks for the PR btw. Good idea.

**Comment by bmoffatt** [comment]
Added the revert commit that makes the test pass, and updating title to match for future release notes

**Review by bmoffatt — APPROVED** [review]

**Pull request merged**
